Update to Google Analytics 4
GSA/digitalgov-pra pull request #375
Opened 2024-05-20 20:28 UTC by nick-mon1

2024-05-21 19:07 UTC, clmedders requested changes
this looks to have an extra script tag?  shouldnt this all be in one script tag?

2024-05-22 20:21 UTC, nick-mon1 commented
@clmedders The first tag loads the script, the second configures it. It's the same as https://github.com/GSA/plainlanguage.gov/pull/435/files

2024-05-23 13:55 UTC, clmedders commented
@nick-mon1 got it i must have just been looking at it wrong!

2024-05-23 16:42 UTC, RileySeaburg approved these changes

2024-05-24 00:08 UTC, merged